include:
  - database/docker-compose.yml

services:
  # Nuxt.js Application
  app:
    container_name: pay-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      db:
        condition: service_healthy
      kong:
        condition: service_started
    environment:
      # Database connection
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}

      # API configuration
      SUPABASE_PUBLIC_URL: http://kong:8000
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}

      # Google API
      NUXT_GOOGLE_API_KEY: ${NUXT_GOOGLE_API_KEY}

      # Node environment
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      # Mount source code for development (remove in production)
      - .:/app
      - /app/node_modules
    networks:
      - default

networks:
  default:
    driver: bri
