catalogs:
  database:
    drizzle-kit: latest
    drizzle-orm: latest
    postgres: latest
  dev:
    '@antfu/eslint-config': latest
    '@iconify-json/tabler': latest
    '@nuxt/eslint': latest
    '@unocss/eslint-plugin': latest
    dotenv: ^17.2.3
    eslint: ^9.37.0
    eslint-plugin-format: latest
    tsx: ^4.20.6
    typescript: latest
    wrangler: latest
  framework:
    '@nuxt/fonts': latest
    '@nuxt/icon': latest
    '@nuxt/image': latest
    '@nuxthub/core': latest
    '@nuxtjs/i18n': latest
    '@vueuse/nuxt': latest
    nuxt: latest
    nuxt-safe-runtime-config: latest
  test:
    '@nuxt/test-utils': latest
    '@vue/test-utils': latest
    happy-dom: ^18.0.0
    playwright-core: latest
    vitest: latest
  ui:
    '@unocss/nuxt': latest
    '@unocss/preset-attributify': latest
    nimiq-css: 1.0.0-beta.120
    nimiq-icons: 1.0.0-beta.120
    reka-ui: latest
    unocss-preset-onmax: latest
  utils:
    consola: latest
    date-fns-tz: latest
    opening_hours: latest
    valibot: latest

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
