catalogs:
  database:
    drizzle-kit: latest
    drizzle-orm: latest
    postgres: ^3.4.7
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@nuxt/eslint': ^1.9.0
    '@unocss/eslint-plugin': ^66.5.2
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    wrangler: latest
  framework:
    '@nuxt/fonts': ^0.11.4
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': 1.11.0
    '@nuxthub/core': latest
    '@nuxtjs/i18n': catalog:framework
    '@vueuse/nuxt': ^13.9.0
    nuxt: latest
    nuxt-safe-runtime-config: ^0.0.3
  test:
    '@nuxt/test-utils': ^3.19.2
    '@vue/test-utils': ^2.4.6
    happy-dom: ^19.0.2
    playwright-core: ^1.55.1
    vitest: ^3.2.4
  ui:
    '@unocss/nuxt': ^66.5.2
    '@unocss/preset-attributify': ^66.5.2
    nimiq-css: 1.0.0-beta.117
    nimiq-icons: 1.0.0-beta.117
    reka-ui: ^2.5.1
    unocss-preset-onmax: 1.0.0-beta.43
  utils:
    consola: ^3.4.2
    date-fns-tz: ^3.2.0
    opening_hours: 3.9.0
    valibot: ^1.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
