catalog:
  dotenv: ^17.2.3
catalogs:
  database:
    drizzle-kit: latest
    drizzle-orm: latest
    postgres: latest
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@iconify-json/tabler': ^1.2.13
    '@nuxt/eslint': ^1.9.0
    '@unocss/eslint-plugin': ^0.66.5
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    tsx: ^4.20.6
    typescript: ^5.7.3
    wrangler: ^4.41.0
  framework:
    '@nuxt/fonts': latest
    '@nuxt/icon': latest
    '@nuxt/image': latest
    '@nuxthub/core': latest
    '@nuxtjs/i18n': latest
    '@vueuse/nuxt': latest
    nuxt: latest
    nuxt-safe-runtime-config: latest
  test:
    '@nuxt/test-utils': latest
    '@vue/test-utils': latest
    happy-dom: ^18.0.0
    playwright-core: latest
    vitest: latest
  ui:
    '@unocss/nuxt': latest
    '@unocss/preset-attributify': latest
    nimiq-css: 1.0.0-beta.120
    nimiq-icons: 1.0.0-beta.120
    reka-ui: latest
    unocss-preset-onmax: latest
  utils:
    '@ai-sdk/openai': ^2.0.44
    ai: ^5.0.60
    consola: ^3.4.2
    date-fns-tz: ^3.2.0
    opening_hours: ^4.1.0
    pathe: ^2.0.3
    valibot: ^1.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
