catalogs:
  database:
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
    postgres: ^3.4.7
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@iconify-json/tabler': ^1.2.23
    '@nuxt/eslint': ^1.9.0
    '@unocss/eslint-plugin': ^66.5.3
    dotenv: ^17.2.3
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    tsx: ^4.20.6
    typescript: ^5.9.3
    wrangler: ^4.42.2
  framework:
    '@nuxt/fonts': ^0.11.4
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': ^1.11.0
    '@nuxthub/core': ^0.9.0
    '@nuxtjs/i18n': ^10.1.0
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.3
    nuxt-safe-runtime-config: ^0.0.3
  test:
    '@nuxt/test-utils': ^3.19.2
    '@vue/test-utils': ^2.4.6
    happy-dom: ^20.0.0
    playwright-core: ^1.56.0
    vitest: ^3.2.4
  ui:
    '@unocss/nuxt': ^66.5.3
    motion-v: ^1.7.2
    nimiq-css: ^1.0.0-beta.133
    nimiq-flags: ^1.0.0-beta.133
    nimiq-icons: ^1.0.0-beta.133
    reka-ui: ^2.5.1
    unocss: ^66.5.3
    unocss-preset-onmax: 1.0.0-beta.47
    vue-sonner: ^2.0.9
  utils:
    '@ai-sdk/openai': ^2.0.52
    ai: ^5.0.70
    consola: ^3.4.2
    date-fns-tz: ^3.2.0
    opening_hours: ^4.1.0
    pathe: ^2.0.3
    valibot: ^1.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
